### ISSUE TITLE
[Bug Report] total_steps property for pen-human dataset

### ISSUE THREAD

**Issue by Howuhh** [Farama-Foundation/Minari#106]
**Describe the bug**
Total steps for "pen-human-v0" dataset is none or doesn't exist. Seems like this is true for all adroit datasets.

**Code example**
```python
import minari

minari.download_dataset("pen-human-v0")
dataset = minari.load_dataset("pen-human-v0")
print(dataset.total_steps)
```

**Additional context**
However, this will work
```python
print(dataset.spec.total_steps)
```
Why doesn't the code just take it out of spec? Why does it either None or re-read from self._data?

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo (**required**)

**Comment by younik** [comment]
Solved with https://github.com/Farama-Foundation/Minari/pull/101
