### ISSUE TITLE
[Bug Report] Serialization failed for BabyAI MissionSpace

### ISSUE THREAD

**Issue by helenlu66** [Farama-Foundation/Minari#123]
**Describe the bug**
When creating a BabyAI dataset, I get the following NotImplementedError `No serialization method available for MissionSpace(<function BabyAIMissionSpace._gen_mission at 0x7f7a93fcdb90>, None)`

**Code example**
```
import gymnasium as gym
import minari
from minari import DataCollectorV0

dataset_id = 'BabyAI-GoToLocal-v0'
env = gym.make(dataset_id)
env = DataCollectorV0(env, record_infos=True, max_buffer_steps=100000)

total_episodes = 100

for _ in range(total_episodes):
    env.reset(seed=123)
    while True:
        # random action policy
        action = env.action_space.sample()
        obs, rew, terminated, truncated, info = env.step(action)
        
        if terminated or truncated:
            break

dataset = minari.create_dataset_from_collector_env(dataset_id=dataset_id, 
                                               collector_env=env,
                                               algorithm_name="Random-Policy"
                                               )
```

**System Info**
Describe the characteristic of your environment:
 * Describe how Gymnasium was installed: pip
 * Operating system: MacOs
 * Python version: 3.7.16

**Additional context**
BabyAI is part of MiniGrid: [BabyAI GoToLocal](https://minigrid.farama.org/environments/babyai/GoToLocal/)

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo (**required**)

**Comment by balisujohn** [comment]
Thanks for your report. It looks like minigrid envs have MissionSpace spaces in their observation spaces https://github.com/Farama-Foundation/Minigrid/blob/546c040a9424f339b7ba69e911e4126cee216e64/minigrid/minigrid_env.py#L78. Minari only supports the spaces listed here: https://minari.farama.org/content/dataset_standards/#supported-spaces. The recommended solution would be to use a StepDataCallback to do so like in this tutorial: https://minari.farama.org/tutorials/dataset_creation/observation_space_subseting/ Crucially, the dataset will have to have a different observation space than the actual env.

**Comment by balisujohn** [comment]
Also, to use this feature, you will need to use minari `0.4.1` which supports pytho3.8 and later. If need to use python3.7, then I would recommend creating a wrapper env for the GoToLocal env with a minari-compliant observation space.

**Comment by balisujohn** [comment]
@rodrigodelazcano I don't think it would hurt to add a tutorial for using StepDataCallback with this environment. I think it would also be good to make this error message `No serialization method available for space)` explicitly say "Minari does not support this space"
