### ISSUE TITLE
[Question] Is there plan to add d4rl mujoco?

### ISSUE THREAD

**Issue by im-Kitsch** [Farama-Foundation/Minari#135]
### Question

Hi, 

I am curious is there any time plan to migrates d4rl mujoco environments to minari? E.g. ant-medium/expert/...-v2/v4, hopper-medium/expert/...-v2/v4/?

Though mujoco's -v2 environments are no longer maintained, but it's still popular baseline for research.

Thanks your great work!

**Comment by balisujohn** [comment]
New (regenerated) datasets with Mujoco v5 environments are under construction for Minari. It seems like there is a lot of demand for ports of the old mujoco datasets in a Minari format (without regenerating the data), so I'm inclined to support offering those as well, though I can't promise a timeline for those.

**Comment by im-Kitsch** [comment]
Hi, @balisujohn , thanks for the reply. I transferrred the mujoco-v2's environment, how I can I make a "PR" to upload dataset?

**Comment by balisujohn** [comment]
@im-Kitsch If you can post a link to where where we can download the datasets in the minari channel in our discord, we can handle getting them set up with our hosting.

**Comment by younik** [comment]
Hey @im-Kitsch, I believe this is solved now, isn't it?

**Comment by im-Kitsch** [comment]
Hey, @younik yes, I will add d4rl transfer later today or tomorrow
