### ISSUE TITLE
looks strange for typing_extensions==4.4.0

### ISSUE THREAD

**Issue by im-Kitsch** [Farama-Foundation/Minari#145]
### Question
Hi, 

it looks strange that the installing requires 4.4.0, since it could cause conflict frequently. 

I checked the usage of typing-extensions, it only used for two places
- Use `TypedDict` as `StepData`, here https://github.com/Farama-Foundation/Minari/blob/ea4097854cae1b333ddd7de2fc3fabd0fbc1076d/minari/data_collector/callbacks/step_data.py#L2 TypedDict is officially support since python 3.8 and minari requires also at least python3.8. 

- Use `Annotated` here, https://github.com/Farama-Foundation/Minari/blob/ea4097854cae1b333ddd7de2fc3fabd0fbc1076d/minari/data_collector/callbacks/step_data.py#L2 
Looks it's mainly designed for cooperating with typer, but typer requires typing-extensions>3.7 . Here (https://github.com/tiangolo/typer/blob/e0b207f3f577cb2e59fdd60da39686a2f5ed0e77/pyproject.toml#L34 )

So, shall the requirement of `typing-extensions==4.4.0` be removed?

**Comment by balisujohn** [comment]
If this doesn't break our pre-commit then I think it's fine, you make a reasonable argument for it.
