### ISSUE TITLE
[Bug Report] Pre-commit error with gymnasium

### ISSUE THREAD

**Issue by im-Kitsch** [Farama-Foundation/Minari#150]
**Describe the bug**
Looks if we wanna to make pre-commit check, it always throws error about typing issue that relates to gymnasium. If the gymnasium is installed, when we do pre-commit, pyright check will give error relates to typing hint of env_spec or like those. If we uninstall gymnasium then the error will dispear.

For more detail, you could check the code example and attached output. I think it's very clear that the error is caused by type hint of `Optional`, the env attribute  could be `None`. E.g. environment's `env_spec` could be None, then `env_spec.make` could be `None.make()` so pyright thorws error. 

Also, I believe in github workflows, if we add step `pip install gymnasium`(or install dependencies of minari) into precommit action, `pre-commit` will thorow error anyway.

**Code example**
To recover, just do so:
```
$ conda create -n test3.11 python=3.11
$ conda activate test3.11
$ git clone git@github.com:Farama-Foundation/Minari.git
$ cd Minari
$ pip install -e . # or run pip install gymnasium
$ pip install pre-commit
$ pre-commit run --all-files
```
Then you could find there is four errors and quite some warnings If we run `$ pip uninstall gymnasium` then the error and warning will disapear.

> xxxxx/Minari/minari/utils.py
>   xxxxx/Minari/minari/utils.py:177:13 - error: Argument of type "Generator[int | None, None, None]" cannot be assigned to parameter "__iterable" of type "Iterable[SupportsRichComparisonT@max]" in function "max"
>     "Generator[int | None, None, None]" is incompatible with "Iterable[SupportsRichComparisonT@max]"
>       TypeVar "_T_co@Iterable" is covariant
>         Type "int | None" cannot be assigned to type "SupportsRichComparison"
>           Type "int | None" cannot be assigned to type "SupportsRichComparison"
>             Type "None" cannot be assigned to type "SupportsRichComparison" (reportGeneralTypeIssues)
>   xxxxx/Minari/minari/utils.py:344:60 - error: Argument of type "ActType@get_average_reference_score" cannot be assigned to parameter "action" of type "WrapperActType@Wrapper" in function "step"
>     Type "ActType@get_average_reference_score" cannot be assigned to type "WrapperActType@Wrapper" (reportGeneralTypeIssues)
> xxxxx/Minari/minari/dataset/minari_dataset.py
>   xxxxx/Minari/minari/dataset/minari_dataset.py:279:41 - warning: "_total_episodes" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/minari/dataset/minari_dataset.py:314:41 - warning: "_total_episodes" is protected and used outside of the class in which it is declared (reportPrivateUsage)
> xxxxx/Minari/tests/common.py
>   xxxxx/Minari/tests/common.py:566:32 - warning: "_buffer" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/common.py:568:28 - warning: "_buffer" is protected and used outside of the class in which it is declared (reportPrivateUsage)
> xxxxx/Minari/tests/data_collector/callbacks/test_step_data_callback.py
>   xxxxx/Minari/tests/data_collector/callbacks/test_step_data_callback.py:104:34 - warning: "_data" is protected and used outside of the class in which it is declared (reportPrivateUsage)
> xxxxx/Minari/tests/dataset/test_dataset_download.py
>   xxxxx/Minari/tests/dataset/test_dataset_download.py:59:34 - warning: "_data" is protected and used outside of the class in which it is declared (reportPrivateUsage)
> xxxxx/Minari/tests/dataset/test_minari_dataset.py
>   xxxxx/Minari/tests/dataset/test_minari_dataset.py:94:32 - warning: "_buffer" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/dataset/test_minari_dataset.py:96:28 - warning: "_buffer" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/dataset/test_minari_dataset.py:107:34 - warning: "_data" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/dataset/test_minari_dataset.py:154:26 - warning: "_data" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/dataset/test_minari_dataset.py:168:32 - warning: "_buffer" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/dataset/test_minari_dataset.py:170:28 - warning: "_buffer" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/dataset/test_minari_dataset.py:199:19 - warning: "_episode_indices" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/dataset/test_minari_dataset.py:200:29 - warning: "_data" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/dataset/test_minari_dataset.py:201:20 - warning: "_data" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/dataset/test_minari_dataset.py:288:19 - warning: "_episode_indices" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/dataset/test_minari_dataset.py:289:29 - warning: "_data" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/dataset/test_minari_dataset.py:290:20 - warning: "_data" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/dataset/test_minari_dataset.py:466:34 - warning: "_data" is protected and used outside of the class in which it is declared (reportPrivateUsage)
> xxxxx/Minari/tests/utils/test_dataset_combine.py
>   xxxxx/Minari/tests/utils/test_dataset_combine.py:74:18 - error: "max_episode_steps" is not a known member of "None" (reportOptionalMemberAccess)
>   xxxxx/Minari/tests/utils/test_dataset_combine.py:75:24 - error: "make" is not a known member of "None" (reportOptionalMemberAccess)
> xxxxx/Minari/tests/utils/test_dataset_creation.py
>   xxxxx/Minari/tests/utils/test_dataset_creation.py:59:32 - warning: "_buffer" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/utils/test_dataset_creation.py:61:28 - warning: "_buffer" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/utils/test_dataset_creation.py:80:34 - warning: "_data" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/utils/test_dataset_creation.py:173:34 - warning: "_data" is protected and used outside of the class in which it is declared (reportPrivateUsage)
>   xxxxx/Minari/tests/utils/test_dataset_creation.py:287:34 - warning: "_data" is protected and used outside of the class in which it is declared (reportPrivateUsage)
> 4 errors, 24 warnings, 0 informations
> Completed in 1.5sec

**System Info**
Describe the characteristic of your environment:
 * Describe how Minari was installed (pip, docker, source, ...): See code example
 * Operating system: MacOS
 * Python version: Python 3.11

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Minari/issues) in the repo (**required**)

**Comment by younik** [comment]
This should be solved now; feel free to open it again if it is not.
