### ISSUE TITLE
[Fix] This line should be updated for gymnasium 1.0.0

### ISSUE THREAD

**Issue by jamartinh** [Farama-Foundation/Minari#176]
The line:

https://github.com/Farama-Foundation/Minari/blob/e24113bf09b5b1769dafbaf6bb0b2c9b8eb9ffbe/minari/utils.py#L15

This currently causes an import error in gymnasium 1.0.0rc

Should be changed to:
```python
from gymnasium.wrappers import RecordEpisodeStatistics
```

**Comment by jamartinh** [comment]
PR done!

**Comment by younik** [comment]
Merged :)
