### ISSUE TITLE
[Question] Does not iterating over episodes should produce "all" the episode data including infos and other stores keys?

### ISSUE THREAD

**Issue by jamartinh** [Farama-Foundation/Minari#178]
### Question

Does not iterating over episodes should produce "all" the episode data including infos and other stores keys?

After that we can use more specific iterators to just select a subset of the keys.

I.e. for what reason we are able to store in MuJoCo Hopper the x-position if when iterating we can't read it? And we cannot access Infos per episode?

**Comment by younik** [comment]
Hey @jamartinh thanks for the question.

We are working on adding infos to the data returned when iterating the episode, see https://github.com/Farama-Foundation/Minari/pull/132

Hopefully, we will have this merged soon and this problem will be solved with the next release!

**Comment by younik** [comment]
This should be solved now with 0.4.3; feel free to open it again if something is missing.
