### ISSUE TITLE
[Question] Compatibility with PettingZoo

### ISSUE THREAD

**Issue by edo-vi** [Farama-Foundation/Minari#190]
### Question

Is this compatible with PettingZoo? I've adapted a Gym environment into a custom PettingZoo environment, and I wanted to use Minari for some Offline RL. However, it seems DataCollector needs an environment instantiated by "gym.make" and whenever I try to make my environment "registrable" I get errors because it seems that the interface required is not really compatible with that of PettingZoo.

Is this a problem of PettingZoo or Minari? Or mine?
Thanks

**Comment by younik** [comment]
Hello @edo-vi,
currently, we don't support PettingZoo, but we plan to do it in the future!

**Comment by edo-vi** [comment]
Dear @younik,
Thanks for the reply!
If that is the case, then I'm looking forward to it!
