### ISSUE TITLE
[Bug Report] Black render image

### ISSUE THREAD

**Issue by zichunxx** [Farama-Foundation/Minari#197]
**Describe the bug**

I have a custom gym env that inherits `MujocoRobotEnv` and wrap it with `DataCollector`.  However, I found all image observations that are stored in `DataCollector` are black. When not using `DataCollector`, a custom environment wrapped by `PixelObservationV0` can successfully obtain a colored image from the `step` function. Besides, the [ValueError](https://github.com/Farama-Foundation/Minari/issues/191) is also triggered when the `info` dict returned by the `step` function is not empty. Below is a minimal working example to reproduce these errors. The `panda_mujoco_gym` env was created by myself and can be required from [here](https://github.com/zichunxx/panda_mujoco_gym).  

Thanks in advance for your precious time in checking this issue!

**Code example**
```
import gymnasium as gym
from gymnasium.experimental.wrappers import PixelObservationV0
import matplotlib.pyplot as plt
from minari import DataCollector
import panda_mujoco_gym

env = gym.make("FrankaPickAndPlaceSparse-v0", render_mode="rgb_array")
env = PixelObservationV0(env, pixels_only=True)
obs, info = env.reset(seed=seed) # rgb image can be observed

env = DataCollector(env, record_infos=True, max_buffer_steps=max_buffer_steps)
obs, info = env.reset(seed=seed)
plt.imshow(obs) # rgb image can not be observed
plt.show()
```

**System Info**
Describe the characteristic of your environment:
 * Describe how Minari was installed (pip, docker, source, ...): pip 
 * Operating system: Ubuntu 20.04
 * Python version: 3.9.18
 * Minari version: 0.4.3

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Minari/issues) in the repo (**required**)

**Comment by younik** [comment]
I am not able to reproduce the error; I get the image with your environment. Are you having the same issue with other environments of `Gymnasium-Robotics`?
![Figure_1](https://github.com/Farama-Foundation/Minari/assets/42100908/07aa97f4-a192-44ee-a791-48dc19bc1edb)


> Besides, the https://github.com/Farama-Foundation/Minari/issues/191 is also triggered when the info dict returned by the step function is not empty.

Please, check the answer in the other issue for this

**Comment by younik** [comment]
Okay, I was able to reproduce the issue now

Mujoco is not able to handle rendering of multiple instance of environment, and we are re-making the environment at DataCollector initialization (when creating a new MinariStorage).

https://github.com/Farama-Foundation/Minari/pull/198 should solve the issue, can you check?
You can install that version with:
```bash
pip install git+https://github.com/younik/Minari.git@fix-mujoco
```
