### ISSUE TITLE
[Bug Report] Misconfigured dataset on remote

### ISSUE THREAD

**Issue by ihholmes-p** [Farama-Foundation/Minari#204]
I've been running into this error lately when trying to `minari download` any dataset. Replicated on both Windows and Linux:

`>minari download door-human-v1`

with the result

`Python\Python310\lib\site-packages\minari\storage\hosting.py:252: UserWarning: Misconfigured dataset named door-human-v1/data/main_data.hdf5 on remote
  warnings.warn(f"Misconfigured dataset named {blob.name} on remote")`

`minari show` on the dataset returns an AssertionError. (It's nicely formatted in the terminal, but does not lend itself to being copy-pasted, so I put the content in the attached .txt file.)
[minarierror.txt](https://github.com/Farama-Foundation/Minari/files/15052105/minarierror.txt)

I tried running the dataset-related test suites, and they all passed. After running them, everything worked fine. But I've replicated this behavior after deleting the datasets folder and reinstalling Minari, both on Windows and Linux (Ubuntu). It's not the worst problem in the world, since at least one of the tests (or some combination of them - I didn't pin down which one) fixes it, but it would be nice to use the datasets without having to clone the repository and run the tests beforehand.

I did edit hosting.py to indicate which blob was returning the error, and it gives `<Blob: minari-datasets, door-human-v1/data/main_data.hdf5, 1713638657975740>`, even if I've deleted the door-human-v1 dataset. I'm guessing there's some sort of corrupt config file that's being referenced, which is not being deleted when Minari is reinstalled, though perhaps it's being deleted and created by the tests? That would make sense, since manually deleting the datasets doesn't update the config file - though it doesn't explain why there would be an error even after they're redownloaded, and it doesn't explain why I ran into this problem in the first place.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Minari/issues) in the repo (**required**)

**Comment by younik** [comment]
Hello @ihholmes-p,

I was doing some tests with `door-human-v1`, sorry for the inconvenience!
Can you check if now is solved?

**Comment by ihholmes-p** [comment]
Hey @younik
I don't get the blob error anymore, but still an assertion error on trying to `minari show` **any** dataset I download. Again, the output does not lend itself to being copy-pasted, so I put it in an attached text file here. 
[minarierror2.txt](https://github.com/Farama-Foundation/Minari/files/15052478/minarierror2.txt)
(I was also getting these errors a day or two ago, which may have been before your testing)

**Comment by younik** [comment]
@ihholmes-p regarding the `minari show` error, it is solved in main, so it will be available with the next release (in a month or so hopefully!)

In case you want to use it, try switching to main version with `pip install git+https://github.com/Farama-Foundation/Minari.git`

**Comment by ihholmes-p** [comment]
You're right, the datasets do work fine in Python despite the `minari show` error.

I figured out the root cause of all my problems - it seems that Minari is not compatible with Python 3.7 (which makes sense, and I doubt many other people are trying to work with a 6-year-old version of Python). If anyone else runs into this or gets a `KeyError: "Can't open attribute (can't locate attribute in name index)"`, it's may be because you're using an outdated Python version.
