### ISSUE TITLE
[Question] Counting total steps takes very long

### ISSUE THREAD

**Issue by kaixin96** [Farama-Foundation/Minari#236]
### Question

The current implementation appears to iterate through the entire dataset to determine the length of each episode and then sums them to get the total number of steps. Is there a more efficient way to achieve this? Per-episode lengths or total steps seem like properties that could be accessed in O(1) time.

Edit: I found `dataset.storage.total_steps` can return the total step very fast without iterating all episodes. Is there any reason why we need to check `if self.episode_indices is None`?

**Comment by younik** [comment]
The reason behind it is that a `MinariDataset` can point to a subset of the data in a `MinariStorage`, for example after `filter_episodes`.

However, I am noticing right now that there is a bug in the implementation that makes `total_steps` always compute. Specifically `self.episode_indices` is always `not None`.

Thanks for pointing this out! Do you want to make a PR to fix it?

To fix it, I would cache the total steps here
https://github.com/Farama-Foundation/Minari/blob/ed39de11c55acb54fab6a05b7a9ddc0e300f2275/minari/dataset/minari_dataset.py#L122-L123

And remove the check here
https://github.com/Farama-Foundation/Minari/blob/ed39de11c55acb54fab6a05b7a9ddc0e300f2275/minari/dataset/minari_dataset.py#L310-L311

**Comment by kaixin96** [comment]
Sorry, I missed the notification. Thank you for the quick fix!
