### ISSUE TITLE
[Bug Report] dataset_id with namespace doesn't match the pattern DATASET_ID_RE on Windows

### ISSUE THREAD

**Issue by kaixin96** [Farama-Foundation/Minari#238]
**Describe the bug**
When using namespace on Windows, loading dataset will lead to an error saying that the dataset_id doesn't match the pattern. Due to different path format on Windows, the dataset_id will be loaded as `<name-space>\\<dataset>-v<version>`, instead of `<name-space>/<dataset>-v<version>`. This triggers the error. I think it can be fixed by either modifying the [recurse_directories function](https://github.com/Farama-Foundation/Minari/blob/v0.5.0/minari/storage/local.py#L77) or updating the regex pattern `DATASET_ID_RE `. I'm happy to submit a PR.

**System Info**
Describe the characteristic of your environment:
 * Describe how Minari was installed (pip, docker, source, ...)： pip, minari=0.5.0
 * Operating system: Windows 11
 * Python version: 3.9.19

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Minari/issues) in the repo (**required**)

**Comment by younik** [comment]
Thanks for pointing this out @kaixin96!

Yes, can you open a PR for it modifying the `recurse_directories` function?
