### ISSUE TITLE
[Bug Report] Discord link does not work 

### ISSUE THREAD

**Issue by Rami-Ismael** [Farama-Foundation/Minari#30]
Ths discord link does not work

**Comment by BalajiAI** [comment]
It should work now !

**Comment by BalajiAI** [comment]
Hi, @Rami-Ismael, You can join the discord server using the link mentioned in [our website](https://farama.org/).

**Comment by jjshoots** [comment]
Seems like our link expires after 7 days. [Here](https://discord.gg/uwmmGNCXwH)'s one that's perpetual, at least until we have to change it again.
