### ISSUE TITLE
[Proposal] Add `download` arg to load_dataset()

### ISSUE THREAD

**Issue by rodrigodelazcano** [Farama-Foundation/Minari#36]
### Proposal
If `download` True fetch dataset name from remote Farama server.

A clear and concise description of the proposal.

### Motivation
This functionality is similar to Pytorch dataset loading

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo (**required**)

**Comment by mguarin0** [comment]
@rodrigodelazcano i'll take this one!
Modifying [this](https://github.com/Farama-Foundation/Minari/blob/9540c5ddb259b46fa7682e3d78bc56572f0d17c8/minari/storage/local.py#L8) function 🔨
