### ISSUE TITLE
[Proposal] Autodocs generation for remote datasets

### ISSUE THREAD

**Issue by rodrigodelazcano** [Farama-Foundation/Minari#44]
# Proposal
Add docs to the webpage for each dataset in the remote GCP bucket (https://minari.farama.org/main/datasets/coming_soon/). Generate the docs automatically wen building the website, this can be done similarly to the [Gymnasium environment docs](https://github.com/Farama-Foundation/Gymnasium/blob/main/docs/scripts/gen_mds.py). 

The side menu in the docs webpage should have the names of the datasets classified by environment `id`:

<details open>
<summary>AdroitHandDoor-v1</summary>
  <p>&nbsp &nbsp door-human-v0<br>
 &nbsp &nbsp door-expert-v0<br>
 &nbsp &nbsp door-cloned-v0</p>
</details>

For the docs of each dataset include the following:

## Dataset Specs

| Spec | Value |
| ------ | -------- |
| `total_episodes`       |       -     |
| `total_timesteps`       |       -     |
| `flatten_observations`       |       -     |
| `flatten_actions`       |       -     |
| `algorithm`       |       -     |
| `code_permalink`       |       -     |
| `author`       |       -     |
| `author email`       |       -     |

These specs can be retrieved from the [`minari.list_remote_datasets()`](https://minari.farama.org/main/api/minari_functions/#minari.list_local_datasets) function

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo (**required**)

**Comment by MaxHuerlimann** [comment]
I will take a look and get you a first version in the next days.

**Comment by rodrigodelazcano** [comment]
Removing in favor of https://github.com/Farama-Foundation/Minari/pull/45
