### ISSUE TITLE
[Bug Report] h5py error when combining more than 2 datasets

### ISSUE THREAD

**Issue by Howuhh** [Farama-Foundation/Minari#56]
**Describe the bug**
Have you tried combining more than two dataset at a time? When I try to do that, I get an error, while combining only two datasets works fine. I think this might be related to the https://github.com/h5py/h5py/issues/1385.

**Error**
```shell
Traceback (most recent call last):
  File "rllib_mini/train_ppo.py", line 171, in <module>
    train()
  File "/usr/local/lib/python3.8/dist-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "rllib_mini/train_ppo.py", line 164, in train
    comdined_dataset = minari.combine_datasets(datasets, new_dataset_id=f"{config.env_name}-dataset-v{config.version}")
  File "/usr/local/lib/python3.8/dist-packages/minari/utils.py", line 132, in combine_datasets
    combined_data_file.attrs["author"] = dataset_file.attrs["author"]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.8/dist-packages/h5py/_hl/attrs.py", line 103, in __setitem__
    self.create(name, data=value)
  File "/usr/local/lib/python3.8/dist-packages/h5py/_hl/attrs.py", line 212, in create
    h5a.delete(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 145, in h5py.h5a.delete
KeyError: 'Unable to delete attribute (record is not in B-tree)'
```

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo (**required**)

**Comment by rodrigodelazcano** [comment]
I had this issue in the past, the hdf5 file didn't like having its attributes override. A patch is to instead use the `modify` method.
I already fixed it for the `total_steps` and `total_episodes` attributes, but missed doing it for `email` and `author_email`.
https://github.com/Farama-Foundation/Minari/blob/45a1b6d9327f899e097c944b9086e847112d54c8/minari/utils.py#L125

I've checked on my end and it works. If you have the time can you make a PR? Having a CI test for this with a generic environment will also be useful

**Comment by Howuhh** [comment]
@rodrigodelazcano I think I will have time for it this week. I also planning to add option for explicit copy during combining. For example in my case I have 200+ small datasets which I want to combine. External link is not very convenient here, as I want to be able to distribute only one dataset file between clusters/machines and delete all the rest.

**Comment by rodrigodelazcano** [comment]
> @rodrigodelazcano I think I will have time for it this week. I also planning to add option for explicit copy during combining. For example in my case I have 200+ small datasets which I want to combine. External link is not very convenient here, as I want to be able to distribute only one dataset file between nodes/machines and delete all the rest (deleting them will break things currently, as I already learned :D).

Sounds good to me, although moving hdf5 groups from one file to another can be a little inefficient that's why I used external links. However, for small datasets it shouldn't be a problem. Can you implement this in the combine function as a boolean arg?
