### ISSUE TITLE
[Question] Bibtex Citation

### ISSUE THREAD

**Issue by DarthMalloc** [Farama-Foundation/Minari#62]
### Question

I was wondering, is there a separate Bibtex citation that we should use specifically for Minari, or should we use the one given for the D4RL project?

**Comment by rodrigodelazcano** [comment]
Hey @DarthMalloc, sorry for the late reply. For now you can cite Minari as follows: (Bibtex)
```
@software{Minari_Contributors_Minari_A_dataset_2023,author = {{Minari Contributors}},month = may,title = {{Minari: A dataset API for Offline Reinforcement Learning}},year = {2023}}
```
